#!/usr/bin/env ruby
#
# This is not a shipped file.  It generates the file named in outputFilename from
# the resx file

require 'rexml/document'

outputFilename = "XSConsoleLangFriendlyNames.py"

if ARGV.size != 1:
  puts "Usage: #{$0} <filename>"
  puts "Please supply the filename for xenadmin.hg/XenAdmin/XenAPI/autogen-enterprise/FriendlyNames.resx"
  abort
end

header = [
"# coding: UTF-8",
"# Copyright (c) Citrix Systems 2008. All rights reserved.",
"# xsconsole is proprietary software.",
"#",
"# Xen, the Xen logo, XenCenter, XenMotion are trademarks or registered",
"# trademarks of Citrix Systems, Inc., in the United States and other",
"# countries.",
"#",
"# Generated by #{File.basename($0)} #{Time.now}",
"# from #{File.basename(ARGV[0])} last modified #{File.mtime(ARGV[0])}",
"",
"class LangFriendlyNames:",
"  @classmethod",
"  def Translate(cls, inTag):",
"    return cls.friendlyNamesMap.get(inTag, inTag)",
"",
"  friendlyNamesMap = {"
]

footer = [
"  }"
]



friendlyNamesMap = {}

file = File.new(ARGV[0])
doc = REXML::Document.new(file)

doc.elements.each('*/data') do |element|
  friendlyNamesMap[element.attributes['name']] = element.elements['value'].text.to_s.gsub("'") { "\\\'" }
end

file.close()

File.open(outputFilename, 'w') do |file|
  header.each { |line| file.write("#{line}\n") }
  friendlyNamesMap.sort.each { |key, value| file.write("    '#{key}' : '#{value}',\n") }
  footer.each { |line| file.write("#{line}\n") }
end
